language: julia
os:
  - linux
  - osx
julia:
  - 0.3
  - 0.4
  - nightly
env:
    - PYTHON=conda
notifications:
  email: false
after_success: 
  - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("SymPy")); using Coverage; Coveralls.submit(process_folder())'